#! /bin/sh
# postrm script for bastet

set -e

if [ "$1" = purge ] ; then
  rm -f /var/games/bastet.scores2
fi

# Automatically added by dh_installmenu/10.10.4ubuntu1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/10.10.4ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0

