#!/bin/bash
RPM_INSTALL_PREFIX=
export RPM_INSTALL_PREFIX
/sbin/ldconfig

if test "$1" != "1"; then 


if [ "1" = "1" ]; then 
    ppddir=/usr/share/ppd 
    # Remove link to PPD file directory 
    [ -d /opt/epson-inkjet-printer-201401w/ppds ] && rmdir /opt/epson-inkjet-printer-201401w/ppds 2> /dev/null 
    [ -h $ppddir/epson-inkjet-printer-201401w ] && [ ! -e $ppddir/epson-inkjet-printer-201401w ] && \
         rm -f $ppddir/epson-inkjet-printer-201401w 
    [ -d $ppddir/epson-inkjet-printer-201401w ] && [ -h $ppddir/epson-inkjet-printer-201401w/ppds ] && \
         [ ! -e $ppddir/epson-inkjet-printer-201401w/ppds ] && rm -f $ppddir/epson-inkjet-printer-201401w/ppds 
fi 


if [ -x /etc/init.d/cups ]; then 
   cups="cups" 
else 
    if [ -x /etc/init.d/cupsys ]; then 
        cups="cupsys" 
    fi 
fi 
if [ ! -z "$cups" ]; then 
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then 
        invoke-rc.d $cups restart 2>/dev/null || true 
    else 
        /etc/init.d/$cups restart 2>/dev/null || true 
    fi 
fi 


fi