#! /bin/sh

set -e

package_name=kdesudo

# remove old divert
if [ "`dpkg-divert --list|grep $package_name$`" != "" ]; then
    rm -f /usr/lib/kde4/libexec/kdesu
    dpkg-divert --package $package_name --rename --remove \
        /usr/lib/kde4/libexec/kdesu
fi

# Automatically added by dh_installdeb/10.10.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/30-baloo-inotify-limit.conf 4:16.04.3-1~ kde-runtime -- "$@"
# End automatically added section


exit 0
