#! /bin/sh -e

case "$1" in
    remove)
        update-alternatives --remove kdesu /usr/lib/kde4/libexec/kdesu-distrib/kdesu
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb/10.10.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/30-baloo-inotify-limit.conf 4:16.04.3-1~ kde-runtime -- "$@"
# End automatically added section


exit 0
