#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p onboard 
fi

# End automatically added section
# Automatically added by dh_icons/10.7.2ubuntu2
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/HighContrast /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section
