#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/php-pear php5-common 1:0 php-pear -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/pear.conf /etc/pear/pear.conf 1:1.10.1+submodules+notgz-5~ php-pear -- "$@"
# End automatically added section
